Info mostro message
MostroP2P/mostro pull request #279
Opened 2024-05-03 06:12 UTC by arkanoider

Added scheduled message with mostro infos - 5 minutes interval.

2024-05-03 15:29 UTC, grunch requested changes
Can you add Mostro version and current main branch commit? if commit number is too much work just add the version and we do the commit part later

2024-05-03 15:29 UTC, grunch commented on src/nip33.rs
> +            ln_settings.hold_invoice_cltv_delta.to_string(),
This value is duplicated

2024-05-03 15:29 UTC, grunch commented on src/scheduler.rs
> +            let id = format!("Mostro npub {} info event", mostro_pubkey.public_key());
`d tag` value shouldn't have white spaces and must be more concise, let's change it to
 
```rust
let id = format!("info-{}", mostro_pubkey.public_key());
```

2024-05-03 15:59 UTC, arkanoider commented on src/nip33.rs
> +            ln_settings.hold_invoice_cltv_delta.to_string(),
Ups! Will remove

2024-05-03 15:59 UTC, arkanoider commented on src/scheduler.rs
> +            let id = format!("Mostro npub {} info event", mostro_pubkey.public_key());
Yep!

2024-05-04 11:26 UTC, arkanoider commented on src/nip33.rs
> +            ln_settings.hold_invoice_cltv_delta.to_string(),
Added both in info message, need to be tested.

2024-05-04 13:18 UTC, grunch approved these changes
LGTM

2024-05-04 13:18 UTC, merged