admin-settle-add-validation
MostroP2P/mostro pull request #323
Opened 2024-07-05 23:36 UTC by Catrya

Now if someone who is not a solver or admin tries to settle an order, they will get CantDo. If they are a solver or admin and the order is not in dispute, mostro will notified that they cannot do because of the status, and if it is in dispute but they did not taken it, will notified correctly.

The way Mostro has been working until now, if a user tries to settle an order regardless of its status and regardless of whether they are an admin or not they will see the message 'Dispute Not taken by you, (except if it was cooperatively canceled). 

@grunch @arkanoider please test it :)

2024-07-06 19:58 UTC, arkanoider reviewed
For me it's a merge! Let's see Francisco...

@Catrya just do a cargo fmt and commit again to format all file in a nice way!

2024-07-06 19:59 UTC, arkanoider approved these changes

2024-07-09 13:22 UTC, grunch requested changes

2024-07-09 13:22 UTC, grunch commented on src/app/admin_settle.rs
> -    match is_assigned_solver(pool, &event.pubkey.to_string(), order_id).await {
same that I asked in the other PR

could you explain why moving this block code to bottom?

2024-08-07 04:08 UTC, Catrya commented
I will close it and then upload it from the new fork I made

2024-08-07 04:08 UTC, closed without merging

2024-08-07 04:08 UTC, Catrya commented
I will close it and then upload it from the new fork I made