When taking an order, check the status first and then the quantity
MostroP2P/mostro pull request #351
Opened 2024-09-02 20:37 UTC by Catrya

fix #349 
Now when someone takes an order Mostro will first check the status of the order and then if it has a range it will check the quantity that was requested to be taken is within the range and not the other way around.

2024-09-03 08:59 UTC, arkanoider commented
@Catrya @grunch ,

i think this is correct, just don't know how `lnp2p` manage this. I mean now a range order cannot be taken from other people until it's completed ( with success or not ) . Is this correct or we want other users can take the same order while it's still active?

2024-09-03 12:48 UTC, arkanoider commented on src/app/take_buy.rs
> +
Moving this call below indeed is avoiding that a user can take another time the offer until it's completed ( successfully or not ). It could be good to me, but I don't know what is the behaviuor of lnp2p in this case, I mean a range order in lnp2p can have two pending orders simoultaneously?

2024-09-03 14:53 UTC, Catrya commented on src/app/take_buy.rs
> +
> Moving this call below indeed is avoiding that a user can take another time the offer until it's completed ( successfully or not ). It could be good to me, but I don't know what is the behaviuor of lnp2p in this case, I mean a range order in lnp2p can have two pending orders simoultaneously?

In lnp2pbot an order can only be taken in `pending` status. If it has a range, until it is completed it is not published again so that someone can take what is left of the range. I suppose that is the expected behavior for Mostro as well, I don't know if @grunch  want to do it differently here

But what is happening now in Mostro is that if someone takes an order with a range but it is already in any other status that is not `pending` because someone else is already taking it, or they are already taking it, if they put that they are going to take it with an amount outside the range, Mostro will respond `OutOfRangeFiatAmount`, and when that person later puts an amount within the range, Mostro will tell them that it is `NotAllowedByStatus`.

So what I propose is to save a step and have Mostro respond from the beginning that it cannot be taken `NotAllowedByStatus`

2024-09-19 19:36 UTC, grunch requested changes
please solve the conflicts

2024-10-07 14:21 UTC, arkanoider commented
If conflicts are over I think this could be merged @grunch , make sense imo.

2024-10-08 12:43 UTC, grunch approved these changes
LGTM

2024-10-08 12:43 UTC, merged