Scheduler new tasks
MostroP2P/mostro pull request #69
Opened 2023-05-04 20:46 UTC by arkanoider

Hi @grunch ,

here a first draft pull request, just tested in a basic case with sell order published --> Taken without invoice --> After 15 minutes order has been republished.

I don't know if my idea is correct, but in the scheduler I check that order is WaitingBuyerInvoice or WaitingPayment and if it's older than 15 minutes I republish the order. Double check with you if it's not correct, anyway we have the scheduler running.

2023-05-05 09:33 UTC, arkanoider commented
Added delay on event rate sending. Not tested just compiled.

2023-05-05 15:06 UTC, grunch requested changes
Testing I have this situation:

* Seller creates and market price order 
* Buyer take it
* Buyer didn't go further
* Order republished correctly but it doesn't clean the amount to 0

Same thing with orders created by buyer and took it by seller

2023-05-05 15:29 UTC, arkanoider commented
Thanks for testing @grunch !
Clear! Will look to fix all this and also the info string with a more coherent message.

2023-05-05 21:55 UTC, arkanoider commented
> Testing I have this situation:
> 
>     * Seller creates and market price order
> 
>     * Buyer take it
> 
>     * Buyer didn't go further
> 
>     * Order republished correctly but it doesn't clean the amount to 0
> 
> 
> Same thing with orders created by buyer and took it by seller

FIxed.

2023-05-06 10:54 UTC, grunch commented
> > Testing I have this situation:
> > ```
> > * Seller creates and market price order
> > 
> > * Buyer take it
> > 
> > * Buyer didn't go further
> > 
> > * Order republished correctly but it doesn't clean the amount to 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Same thing with orders created by buyer and took it by seller
> 
> FIxed.

Great, now I found that in this case it should set to null `master_buyer_pubkey` too, and in the case where the buyer is the maker the `master_seller_pubkey` should be set to null too.

2023-05-06 15:08 UTC, arkanoider commented
> Testing I have this situation:
> 
>     * Seller creates and market price order
> 
>     * Buyer take it
> 
>     * Buyer didn't go further
> 
>     * Order republished correctly but it doesn't clean the amount to 0
> 
> 
> Same thing with orders created by buyer and took it by seller

FIxed.

> > > Testing I have this situation:
> > > ```
> > > * Seller creates and market price order
> > > 
> > > * Buyer take it
> > > 
> > > * Buyer didn't go further
> > > 
> > > * Order republished correctly but it doesn't clean the amount to 0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Same thing with orders created by buyer and took it by seller
> > 
> > 
> > FIxed.
> 
> Great, now I found that in this case it should set to null `master_buyer_pubkey` too, and in the case where the buyer is the maker the `master_seller_pubkey` should be set to null too.

Hi @grunch ,workin on this...just a doubt...

Seller creates order --> Buyer takes it --> No other actions from buyer --> Order reset to pending and also set to None master_buyer_pubkey

Buyer creates order --> Seller takes it --> No other actions from seller --> Order reset to pending and also set to None master_seller_pubkey ( and also master buyer ?? Don't understand if both need to go to None )

2023-05-06 16:01 UTC, grunch commented
> 

the counterpart fields must be set to null again, we need to reset the order to the exact same state that it was before was taken.

2023-05-06 16:03 UTC, arkanoider commented
> > 
> 
> the counterpart fields must be set to null again, we need to reset the order to the exact same state that it was before was taken.

Yes...just the counterpart right? not both...

2023-05-06 17:07 UTC, grunch commented
> > > 
> > 
> > the counterpart fields must be set to null again, we need to reset the order to the exact same state that it was before was taken.
> 
> Yes...just the counterpart right? not both...

the correct response is the order record must be the same than before, in this particular case only the counterpart should be reset but in other cases some fields of the maker should be reset too

2023-05-06 17:25 UTC, arkanoider commented
> > > > 
> > > 
> > > 
> > > the counterpart fields must be set to null again, we need to reset the order to the exact same state that it was before was taken.
> > 
> > 
> > Yes...just the counterpart right? not both...
> 
> the correct response is the order record must be the same than before, in this particular case only the counterpart should be reset but in other cases some fields of the maker should be reset too

Yes clear...i am.doing all the case chart to understand

2023-05-07 21:23 UTC, arkanoider commented
Working on scheduler @arkanoider , will add taken_at management to align to lnp2pbot cancel/republish logics.

2023-05-07 21:53 UTC, grunch commented on src/db.rs
> +        seller_dispute,
`seller_dispute` is missing here

2023-05-08 12:45 UTC, grunch commented on src/scheduler.rs
> +            // for or in older_orders_list.unwrap().into_iter(){
please remove commented code

2023-05-08 20:45 UTC, grunch approved these changes
LGTM 😄

2023-05-08 20:45 UTC, merged